/**
 * Spec 015 test plan: the single source for the unit tests and for the table in
 * docs/specs/015-review-queue/spec.md (`bun run docs:test-plan` regenerates it).
 * Inputs are real values captured 2026-10-08 (docs/specs/015-review-queue/samples/: github-open-prs.json,
 * feed-kip-mail-entries.json, ponymail-kip-threads.json), except rows
 * whose `input` starts with "constructed:". `now` for PR rows is 2026-10-08T04:01:48Z, for KIP rows
 * 2026-10-08T04:03:37Z. Kafka profile: reviewWaitDays 14, fewRepliers 2, proposal votes {quorum 3, lazy-majority, 72 h, committer}.
 * Slice 1 (deterministic core) rows; slice 2 and 3 rows are in review-queue-run.cases.ts and review-queue-ui.cases.ts.
 */
export const testPlanRows = [
  { id: "Q1", rule: "snapshot", input: "apache/kafka open PRs, totalCount 625, pages of 100", expected: "7 requests; 625 PRs" },
  { id: "Q1", rule: "snapshot", input: "constructed: PR #23700 on page 2 and again on page 3 (moved while paging)", expected: "counted once" },
  { id: "Q1", rule: "snapshot", input: "constructed: totalCount 625 on page 1, 624 distinct PRs read (one closed while paging)", expected: "snapshot of 624" },
  { id: "Q2", rule: "machine", input: "reviewer copilot-pull-request-reviewer (__typename Bot)", expected: "machine" },
  { id: "Q2", rule: "machine", input: "constructed: author dependabot[bot] (__typename Bot)", expected: "machine; PR not queued" },
  { id: "Q2", rule: "machine", input: "constructed: reviewer codecov-commenter (__typename User) listed in the profile machineUsers", expected: "machine" },
  { id: "Q2", rule: "machine", input: "constructed: reviewer abbott (__typename User, not listed)", expected: "human" },
  { id: "Q2", rule: "machine", input: "#20995 author null (deleted account)", expected: "human author shown as ghost; noReviewer, 315 d" },
  { id: "Q3", rule: "author update", input: "#23724 created 2026-10-07, last timeline item force-push 2026-10-07T16:46:00Z", expected: "author update 2026-10-07T16:46:00Z" },
  { id: "Q3", rule: "author update", input: "#22319 last commit committedDate 2026-05-18T19:33:37Z, human review smjn APPROVED 2026-05-20T18:59:58Z", expected: "waiting since 2026-05-20T18:59:58Z; 140 d" },
  { id: "Q3", rule: "author update", input: "constructed: PR with no timeline item of the 4 types, createdAt 2026-09-01T00:00:00Z", expected: "author update 2026-09-01T00:00:00Z" },
  { id: "Q3", rule: "author update", input: "constructed: author comment 2026-10-07 after the last review, no new commit", expected: "not an author update (comments are not read)" },
  { id: "Q4", rule: "bucket", input: "#22751 isDraft true", expected: "not queued" },
  { id: "Q4", rule: "bucket", input: "#23739 reviewDecision APPROVED, 4 reviewers, commit 2026-10-08T03:08:51Z after the approvals", expected: "approved; 0 d" },
  { id: "Q4", rule: "bucket", input: "#18706 no requested reviewer, no review, created 2025-01-25T13:28:22Z", expected: "noReviewer; 620 d" },
  { id: "Q4", rule: "bucket", input: "#19236 1 reviewer, author update 2025-10-25T20:04:34Z after the last review", expected: "waiting; 347 d" },
  { id: "Q4", rule: "bucket", input: "#23381 reviewer present, author update after the last review, wait 14.32 d", expected: "waiting" },
  { id: "Q4", rule: "bucket", input: "#22996 reviewer present, author update after the last review, wait 13.58 d", expected: "not queued (14 d or less)" },
  { id: "Q4", rule: "bucket", input: "constructed: author update at exactly the last review's submittedAt, wait 30 d", expected: "not queued (not after the review)" },
  { id: "Q4", rule: "bucket", input: "constructed: author update after the last review, wait exactly 14 d 0 ms", expected: "not queued" },
  { id: "Q4", rule: "bucket", input: "constructed: author update after the last review, wait 14 d + 1 ms", expected: "waiting" },
  { id: "Q4", rule: "bucket", input: "constructed: reviewer reviewed after the author's last update (author's turn), wait 40 d", expected: "not queued" },
  { id: "Q4", rule: "bucket", input: "captured snapshot, 625 open PRs", expected: "approved 22; noReviewer 310; waiting 61; not queued 232 (35 drafts, 90 author's turn, 44 waiting on reviewers 14 d or less, 63 without a reviewer 14 d or less)" },
  { id: "Q4", rule: "bucket", input: "#23724 no reviewer (Copilot only), wait 0.5 d", expected: "not queued (no reviewer, 14 d or less)" },
  { id: "Q4", rule: "bucket", input: "constructed: no reviewer, wait exactly 14 d 0 ms", expected: "not queued" },
  { id: "Q4", rule: "bucket", input: "constructed: no reviewer, wait 14 d + 1 ms", expected: "noReviewer" },
  { id: "Q5", rule: "order", input: "no-reviewer bucket of the captured snapshot", expected: "first three #18706 620 d, #18715 618 d, #18808 608 d" },
  { id: "Q5", rule: "order", input: "constructed: #100 and #99 both 30 d", expected: "#99 before #100" },
  { id: "Q5", rule: "home block", input: "column summaries of the captured snapshot and KIP rows", expected: "PR column 393 (310 / 61 / 22), rows #18706 620 d, #18715 618 d, #18808 608 d; KIP column 14 (5 votes / 9 discussions), rows KIP-1375 30 d, KIP-785 20 d, KIP-1377 20 d (tie broken by proposal number)" },
  { id: "Q6", rule: "card label", input: "#23724 in the snapshot, Copilot review only", expected: "Awaiting reviewer" },
  { id: "Q6", rule: "card label", input: "#23739 in the snapshot, 4 human reviewers", expected: "In review · 4 reviewers" },
  { id: "Q6", rule: "card label", input: "#16808 in the snapshot, 1 requested reviewer, no review", expected: "In review · 1 reviewer" },
  { id: "Q6", rule: "card label", input: "constructed: merged PR #23623 (not in the open snapshot)", expected: "no label" },
  { id: "Q6", rule: "card label", input: "#22751 isDraft true", expected: "no label" },
  { id: "Q7", rule: "kip candidates", input: "Dev release 2026-10-08T03-07-37-000Z: 21 dev@ threads with [VOTE]/[DISCUSS] and a KIP key", expected: "6 vote threads; 15 discuss threads" },
  { id: "Q7", rule: "kip candidates", input: "KIP-1349 has [VOTE] KAFKA-MAIL-82e0d5b3 and [DISCUSS] KAFKA-MAIL-4bc41094", expected: "vote row only" },
  { id: "Q7", rule: "kip candidates", input: "DISCUSS: KIP-1378 … (no brackets)", expected: "not a candidate (profile tag is [DISCUSS])" },
  { id: "Q7", rule: "kip candidates", input: "constructed: [RESULT][VOTE] KIP-1279 thread in the release", expected: "KIP-1279 vote row removed" },
  { id: "Q7", rule: "kip candidates", input: "constructed: two [VOTE] KIP-9 threads, last activity 09-01 and 10-01", expected: "the 10-01 thread" },
  { id: "Q7", rule: "kip candidates", input: "constructed: profile apache-datafusion proposal.kind null", expected: "no KIP candidates" },
  { id: "Q7", rule: "kip candidates", input: "constructed: the Kafka profile and entries with proposal.kind set to null", expected: "no KIP candidates" },
  { id: "Q8", rule: "repliers", input: "KAFKA-MAIL-a9696e08 KIP-1163: release has 1 message; full thread 22 messages, root Ivan Yurchenko 2025-04-23", expected: "5 repliers; not few" },
  { id: "Q8", rule: "repliers", input: "KAFKA-MAIL-3bc971ac KIP-1376: root Mickael Maison, replies Paolo Patierno and Mickael Maison", expected: "1 replier; last reply 2026-10-07T13:07:14Z" },
  { id: "Q8", rule: "repliers", input: "KAFKA-MAIL-dd798156 KIP-1375: root only, 2026-09-08T03:17:45Z", expected: "0 repliers; no replies · opened 30 d ago" },
  { id: "Q8", rule: "repliers", input: "constructed: two replies from \"unknown sender\"", expected: "1 replier" },
  { id: "Q8", rule: "repliers", input: "constructed: replies from Alice and \"CI Bot\", profile machineUsers [\"CI Bot\"]", expected: "1 replier" },
  { id: "Q8", rule: "members", input: "constructed: reply \"[EXTERNAL] RE: [VOTE] KIP-9: x\" and \"SV: [VOTE] KIP-9: x\"", expected: "both members" },
  { id: "Q8", rule: "members", input: "constructed: reply \"Re: [VOTE] KIP-9 (was: x)\" in the tree, subject key differs", expected: "not a member; tally incomplete: 1 reply not attributed" },
  { id: "Q8", rule: "members", input: "KAFKA-MAIL-0b57fb00 KIP-785: only message \"Re: [DISCUSS] KIP-785 …\" by Manan Gupta 2026-09-17, no parent", expected: "root not archived; \"seen ≥ 1 replier\"; queued" },
  { id: "Q8", rule: "members", input: "constructed: [VOTE] KIP-9 started as a reply inside the [DISCUSS] KIP-9 tree", expected: "vote row uses only the [VOTE] messages; root = oldest [VOTE] message without a reply prefix" },
  { id: "Q9", rule: "vote line", input: "Andrew Schofield: \"+1 (binding)\"", expected: "+1, declared binding" },
  { id: "Q9", rule: "vote line", input: "Luke Chen: \"+1 (binding) from me.\"", expected: "+1, declared binding" },
  { id: "Q9", rule: "vote line", input: "Alieh Saeedi: \"+1 (non-binding)\"", expected: "+1, declared non-binding" },
  { id: "Q9", rule: "vote line", input: "Bill Bejeck: \"+1 (biding)\"", expected: "+1, declared binding" },
  { id: "Q9", rule: "vote line", input: "José Armando García Sancio: \"+1. LGTM. Looking forward to …\"", expected: "+1, unmarked" },
  { id: "Q9", rule: "vote line", input: "Andrew Schofield: \"Thanks for the KIP.\" then quoted \"> +1 (binding)\"", expected: "no vote (quoted)" },
  { id: "Q9", rule: "vote line", input: "constructed: \"+1 to Chris's suggestion\"", expected: "unclear" },
  { id: "Q9", rule: "vote line", input: "Federico Valeri: \"+1 (non-binding): Vaquar Khan\" (vote summary)", expected: "unclear" },
  { id: "Q9", rule: "vote line", input: "Gabriella Fu: \"0-1. Version 1 was introduced by KIP-1331 …\"", expected: "no vote" },
  { id: "Q9", rule: "vote line", input: "constructed: \"I am +1 on this\" (not at line start)", expected: "no vote" },
  { id: "Q9", rule: "vote line", input: "constructed: \"+1 (binding) - Mickael Maison\" (vote summary)", expected: "unclear" },
  { id: "Q9", rule: "vote line", input: "constructed: \"+1 (binding).\"", expected: "+1, declared binding" },
  { id: "Q9", rule: "vote line", input: "constructed: \"-1 (binding) until the upgrade path is documented\"", expected: "-1, declared binding" },
  { id: "Q9", rule: "vote line", input: "constructed: \"-1: the upgrade path is missing\"", expected: "-1, unmarked" },
  { id: "Q9", rule: "vote line", input: "constructed: \"+1: looks good\"", expected: "unclear" },
  { id: "Q9", rule: "vote line", input: "constructed: \"+1;\"", expected: "+1, unmarked" },
  { id: "Q9", rule: "vote line", input: "constructed: \"Thanks\", \"From: Bob\", then an unquoted \"+1 (binding)\"", expected: "no vote; message ambiguous (vote-like line after a quoted header)" },
  { id: "Q9", rule: "vote line", input: "constructed: \"On Mon, … wrote:\", \"> Please vote\", then \"+1 (binding)\" (bottom-posted)", expected: "+1, declared binding" },
  { id: "Q9", rule: "vote line", input: "constructed: \"-----Original Message-----\" then \"+1 (binding)\"", expected: "no vote (quoted message)" },
  { id: "Q10", rule: "binding", input: "José Armando García Sancio unmarked +1; name in the ASF kafka committer roster (roles committer, pmc)", expected: "binding via roster" },
  { id: "Q10", rule: "binding", input: "KIP-1349: Sushant Mahajan unmarked +1; roster roles committer (not pmc)", expected: "binding via roster (proposal votes need committer)" },
  { id: "Q10", rule: "binding", input: "constructed: roster member writes \"+1 (non-binding)\"", expected: "not binding (declaration wins)" },
  { id: "Q10", rule: "binding", input: "KIP-1279: vaquar khan unmarked +1; not in the roster", expected: "not binding; counted as unmarked" },
  { id: "Q10", rule: "binding", input: "constructed: release vote; Sushant Mahajan unmarked +1 (committer, not pmc)", expected: "not binding (release votes need pmc); counted as unmarked" },
  { id: "Q10", rule: "binding", input: "constructed: \"José Armando García Sancio\" written with a decomposed accent (NFD)", expected: "matches after NFC normalization" },
  { id: "Q10", rule: "binding", input: "constructed: voter \"jose armando garcia sancio\"", expected: "no match (no case folding or transliteration)" },
  { id: "Q11", rule: "voter", input: "KIP-1349: Sushant Mahajan from su…@gmail.com \"+1\" 17:38:50Z, from sm…@apache.org empty reply 18:05:01Z", expected: "1 voter, +1" },
  { id: "Q11", rule: "voter", input: "constructed: A \"+1 (binding)\" then later \"-1 (binding)\"", expected: "A counts -1 binding" },
  { id: "Q11", rule: "voter", input: "constructed: one body with \"+1 (binding)\" then \"-1 (binding)\" lines", expected: "counts -1 binding (last line in the body)" },
  { id: "Q12", rule: "vote row", input: "KAFKA-MAIL-82e0d5b3 KIP-1349: full thread 6 messages, root 2026-08-19", expected: "+1 × 2 · binding 2 of 3 (1 via roster); short; queued" },
  { id: "Q12", rule: "vote row", input: "KAFKA-MAIL-e903d023 KIP-1262: Luke Chen declared, Sancio via roster", expected: "+1 × 2 · binding 2 of 3 (1 via roster); short; queued" },
  { id: "Q12", rule: "vote row", input: "KAFKA-MAIL-86ae8b63 KIP-1368: root only", expected: "+1 × 0 · binding 0 of 3; short; queued" },
  { id: "Q12", rule: "vote row", input: "KAFKA-MAIL-a614bccc KIP-1097: 3 messages, no vote line", expected: "+1 × 0 · binding 0 of 3; short; queued" },
  { id: "Q12", rule: "vote row", input: "KAFKA-MAIL-75914579 KIP-1357: Lucas Brutschy, Matthias J. Sax, Bill Bejeck declared binding, root 2026-06-25", expected: "+1 × 4 · binding 3 of 3; passing; not queued" },
  { id: "Q12", rule: "vote row", input: "KAFKA-MAIL-ff6d44a5 KIP-1279: Mickael Maison, Andrew Schofield, Rajini Sivaram binding; vaquar khan unmarked (not a committer); 1 unclear +1 line", expected: "seen +1 × 4 · binding ≥ 3 of 3 · 1 unmarked; 1 unclear line; unresolved; queued" },
  { id: "Q12", rule: "discuss row", input: "KIP-1153: 2 repliers", expected: "not queued (2 is not fewer than 2)" },
  { id: "Q12", rule: "discuss row", input: "KIP-1379: 1 replier", expected: "queued" },
  { id: "Q12", rule: "discuss row", input: "11 discuss threads without a vote thread", expected: "9 queued (KIP-1375, KIP-1377, KIP-1165 with 0; KIP-785 seen ≥ 1; KIP-1371, KIP-1365, KIP-1379, KIP-1342, KIP-1376 with 1); KIP-1153 and KIP-1163 not" },
  { id: "Q13", rule: "counts", input: "queue object with stored counts {noReviewer 310, waiting 61, approved 22, vote 5, discuss 9}", expected: "accepted; counts equal the arrays" },
  { id: "Q13", rule: "counts", input: "constructed: stored noReviewer 309 with 310 rows", expected: "rejected: counts-mismatch" },
  { id: "Q14", rule: "cite", input: "#18706", expected: "https://github.com/apache/kafka/pull/18706" },
  { id: "Q14", rule: "cite", input: "KIP-1349 vote row", expected: "https://lists.apache.org/thread/ow8p1n05rob9n3k4b7xw8m8zqx4molbl and /#/feed/KAFKA-MAIL-82e0d5b3" },
  { id: "Q16", rule: "wording", input: "KIP-1349, all 6 bodies read, root archived, roster read", expected: "\"+1 × 2 · binding 2 of 3 (1 via roster)\"" },
  { id: "Q16", rule: "wording", input: "constructed: KIP-1349 with Andrew Schofield's message unread", expected: "\"seen +1 × 1 · binding ≥ 1 of 3 (1 via roster); 1 message unread\"; short" },
  { id: "Q16", rule: "wording", input: "KIP-1279 with 1 unclear line", expected: "\"seen +1 × 4 · binding ≥ 3 of 3 · 1 unmarked; 1 unclear line\"" },
  { id: "Q16", rule: "wording", input: "constructed: 3 declared binding +1 and a reply with an unquoted \"+1 (binding)\" below a \"From:\" header, open 100 h", expected: "\"seen +1 × 3 · binding ≥ 3 of 3; 1 message with a vote after a quoted header\"; unresolved" },
  { id: "Q16", rule: "wording", input: "constructed: vote thread whose members are all replies, one \"+1 (binding)\"", expected: "\"seen +1 × 1 · binding ≥ 1 of 3; thread start not archived\"" },
  { id: "Q19", rule: "graphql errors", input: "constructed: HTTP 200, data null, errors[0] \"Something went wrong\" (no path)", expected: "failureKind schema" },
  { id: "Q19", rule: "graphql errors", input: "constructed: HTTP 200, data present, errors[0] path [\"repository\"] (not a PR node)", expected: "failureKind schema" },
  { id: "Q20", rule: "paging drift", input: "constructed: hasNextPage true with an empty nodes list", expected: "failureKind schema (no endless loop)" },
  { id: "Q21", rule: "reopened", input: "#16808 created 2024-08-06, reopened 2026-08-26T05:25:22Z, 1 requested reviewer", expected: "waiting since 2026-08-26T05:25:22Z; 42 d" },
  { id: "Q22", rule: "force-push", input: "#21333 CHANGES_REQUESTED 2026-08-14, force-push 2026-09-02T10:01:16Z", expected: "waiting; 35 d" },
  { id: "Q23", rule: "bot reviewer", input: "#23724 only review by copilot-pull-request-reviewer", expected: "0 reviewers" },
  { id: "Q23", rule: "bot reviewer", input: "constructed: only requested reviewer is a Bot", expected: "0 reviewers" },
  { id: "Q23", rule: "reviewers", input: "constructed: only review is the PR author's own COMMENTED review", expected: "0 reviewers" },
  { id: "Q23", rule: "reviewers", input: "constructed: requested team apache/kafka-committers, no review", expected: "1 reviewer (team)" },
  { id: "Q24", rule: "no decision", input: "constructed: reviewDecision null, one human APPROVED review", expected: "not approved; bucket by reviewers" },
  { id: "Q28", rule: "unparsable", input: "constructed: thread.lua returns HTML", expected: "parse failure, not 0 repliers" },
  { id: "Q28", rule: "unparsable", input: "constructed: thread.lua JSON without thread.epoch", expected: "parse failure, not 0 repliers" },
  { id: "Q28", rule: "unparsable", input: "constructed: thread.epoch as the string \"1790000000\"", expected: "parse failure, not 0 repliers" },
  { id: "Q29", rule: "roster", input: "KIP-1262 with no roster: Luke Chen declared, Sancio unmarked", expected: "\"seen +1 × 2 · binding ≥ 1 of 3; roster unavailable\"; short; queued" },
  { id: "Q46", rule: "node error", input: "constructed: errors[0].path [\"repository\",\"pullRequests\",\"nodes\",17,\"author\"] on page 2", expected: "that PR dropped; droppedNodes 1; page parsed" },
  { id: "Q47", rule: "truncated", input: "constructed: reviewRequests totalCount 12, 10 nodes read, no review", expected: "\"In review · ≥ 10 reviewers\"; not noReviewer" },
  { id: "Q47", rule: "truncated", input: "#23739 latestReviews totalCount 4, 4 nodes", expected: "4 reviewers (exact)" },
  { id: "Q49", rule: "governance", input: "Kafka profile", expected: "asfPreset(kafka, dev) + overrides; roster {asf, kafka}; proposal {quorum 3, lazy-majority, 72 h, committer}; release {quorum 3, lazy-majority, 72 h, pmc}; reviewWaitDays 14; fewRepliers 2" },
  { id: "Q49", rule: "governance", input: "DataFusion profile", expected: "asfPreset(datafusion, dev) with proposal.kind null; no KIP candidates" },
  { id: "Q49", rule: "governance", input: "asfPreset({project: \"kafka\", devList: \"dev\"})", expected: "mail list dev@kafka.apache.org; tags VOTE, DISCUSS, RESULT; roster adapter asf" },
  { id: "Q49", rule: "governance", input: "constructed: proposal.kind KIP and no proposal vote rule", expected: "error: governance has no proposal vote rule" },
  { id: "Q50", rule: "roster", input: "samples/asf-roster-kafka.json", expected: "73 entries; 44 with pmc; smjn Sushant Mahajan [committer]; jsancio José Armando García Sancio [committer, pmc]" },
  { id: "Q50", rule: "roster", input: "constructed: LDAP file also has projects.flink", expected: "only kafka entries kept" },
  { id: "Q50", rule: "roster", input: "constructed: owners [\"p\"], members [\"c\"]", expected: "c [committer]; p [committer, pmc]" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 3, binding -1 × 0, open exactly 72 h", expected: "passing; not queued" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 3, open 71 h 59 min", expected: "pending-close; not queued" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 3, binding -1 × 3, open 100 h", expected: "contested; queued" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 4, binding -1 × 1, open 100 h", expected: "passing; shows binding -1 × 1" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 3 and \"-1 (binding) until …\", open 100 h", expected: "passing; shows binding -1 × 1" },
  { id: "Q51", rule: "vote state", input: "KIP-1279: binding +1 × 3 and an unclear +1 summary line", expected: "unresolved; queued (an unclear line makes the tally a lower bound)" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 3 and \"-1: no\" from a roster committer, open 100 h", expected: "passing; shows binding -1 × 1" },
  { id: "Q51", rule: "vote state", input: "constructed: binding +1 × 3 declared, 1 body unread, open 100 h", expected: "unresolved; queued" },
  { id: "Q51", rule: "vote state", input: "constructed: no roster; binding +1 × 3 declared and an unmarked \"-1.\", open 100 h", expected: "unresolved; queued; \"seen +1 × 3 · binding ≥ 3 of 3 · 1 unmarked -1; roster unavailable\"" },
  { id: "Q53", rule: "via roster", input: "KIP-1262", expected: "binding 2 of 3 (1 via roster)" },
  { id: "Q53", rule: "via roster", input: "KIP-1357: all 3 binding declared", expected: "no \"via roster\" part" },
  { id: "Q54", rule: "roster", input: "constructed: members has id \"ghostid\" with no people entry", expected: "entry {id ghostid, name null}; never matches" },
  { id: "Q55", rule: "roster", input: "constructed: LDAP file without projects.kafka", expected: "roster failure; declared markers only" },
  { id: "Q55", rule: "roster", input: "constructed: projects.kafka with no members field", expected: "roster failure" },
  { id: "Q56", rule: "vote state", input: "constructed: root not archived, binding +1 × 3, newest message 10 d old", expected: "unresolved (a seen tally is never passing); queued" },
];
