/**
 * Spec 014 test plan, slice 2 (DigestRun in the data Worker): rows that need the run loop, the
 * model clients, or the cache. Rendered into docs/specs/014-topic-digest/spec.md by
 * `bun run docs:test-plan`; run by apps/data-publisher-worker/test/digest-run.test.ts (slice 2).
 */
export const testPlanRows = [
  { id: "D10", rule: "cache", input: "constructed: previous digest has KAFKA-PR-23426 with the same model-input hash and classifier revision", expected: "features reused, 0 model calls for it" },
  { id: "D10", rule: "cache", input: "constructed: same model-input hash, classifier prompt revision changed", expected: "reclassified" },
  { id: "D10", rule: "cache", input: "constructed: no new records, but the window slid past the oldest excerpt (input text changed)", expected: "reclassified" },
  { id: "D10", rule: "cache", input: "constructed: card input set and summarizer revision unchanged", expected: "summary reused, 0 model calls" },
  { id: "D13", rule: "model down", input: "constructed: binding throws (network) twice for a classify batch", expected: "1 retry after 5 s; batch gets rules features; fallbacks +20" },
  { id: "D13", rule: "model down", input: "constructed: summary call returns 3040 (capacity) then succeeds", expected: "1 retry; generated" },
  { id: "D13", rule: "model down", input: "constructed: binding throws an error with no recognizable code, twice", expected: "1 retry; batch gets rules features (unidentified errors are retried like 3040)" },
  { id: "D13", rule: "model down", input: "constructed: every call fails", expected: "digest published; all cards fallback (keywords + threads); KIP block unchanged" },
  { id: "D14", rule: "rate limit", input: "constructed: error 3036 (daily free allocation used)", expected: "no retry; remaining calls skipped; limited true; fallback" },
  { id: "D14", rule: "rate limit", input: "constructed: AI Gateway 429 (gateway rate limit)", expected: "no retry; remaining calls skipped; limited true; fallback" },
  { id: "D17", rule: "empty", input: "constructed: 0 candidates", expected: "digest published, empty true, 0 model calls" },
  { id: "D9", rule: "provenance", input: "constructed: a generated card, a proposal line, and a model feature", expected: "each records model, prompt revision, input record ids (cards and rows), generatedAt; cards and rows reviewStatus unreviewed" },
  { id: "D55", rule: "highlights call", input: "constructed: the headline-and-highlights call fails twice", expected: "fallback highlights, no headline; run continues" },
  // Slice 2 rows: translation, publication, recovery, and run control.
  { id: "D50", rule: "translate", input: "constructed: the translation batch returns non-JSON twice", expected: "1 retry of that batch only; every item in it Not translated; zh-Hant published" },
  { id: "D50", rule: "translate", input: "constructed: the translation omits one item and adds an unknown id", expected: "that item Not translated; unknown id ignored; the rest translated" },
  { id: "D61", rule: "recovery", input: "constructed: en written, crash before zh-Hant", expected: "retry writes zh-Hant then the pointer; 0 classify or summary calls" },
  { id: "D61", rule: "recovery", input: "constructed: published zh-Hant has a Not translated item", expected: "next run translates only the Not translated items; new zh-Hant has 0 Not translated" },
  { id: "D19", rule: "recovery", input: "constructed: en and zh-Hant written, crash before the pointer", expected: "previous pointer served until the retry; retry writes only the pointer, 0 model calls" },
  { id: "D19", rule: "recovery", input: "constructed: a limited en for the same release", expected: "next run publishes a new pair; the limited en is used as a cache" },
  { id: "D11", rule: "publication", input: "constructed: a run with a fake model", expected: "writes en, then zh-Hant, then the pointer {schema, objectKeys, sourceReleaseId}" },
  { id: "D20", rule: "publication", input: "constructed: a new Feed release is published while the run reads Details", expected: "digest names the pinned release; no object from the new release is read" },
  { id: "D37", rule: "highlights", input: "constructed: the fake model returns a headline and 3 highlights citing kept sentences", expected: "headline and 3 highlights published, each validated" },
  { id: "D59", rule: "deferral", input: "constructed: publisher running at 4 consecutive alarms", expected: "re-armed 15 min later each time; no run" },
  { id: "D59", rule: "deferral", input: "constructed: publisher still running at the 5th alarm", expected: "runs; lastRun.deferred 4" },
  { id: "D22", rule: "run control", input: "constructed: POST /digest/run while an alarm is pending", expected: "409 already-running" },
  { id: "D22", rule: "run control", input: "constructed: digest cron unset; cron 7 * * * * fires", expected: "publisher" },
  { id: "D22", rule: "run control", input: "constructed: digest cron 37 1 * * * set; it fires", expected: "digest" },
  { id: "D60", rule: "dry run", input: "constructed: POST /digest/run?dryRun=1", expected: "returns en and zh-Hant; 0 R2 writes; spend added to today; lastRun.dryRun true" },
  // Rows added after the slice 2 mutation run.
  { id: "D14", rule: "rate limit", input: "constructed: today's estimated spend already at the Dev cap (4,500)", expected: "no model call; limited true; rules features and fallback cards" },
  { id: "D19", rule: "recovery", input: "constructed: an en with a model fallback (a card's summary failed) for the same release", expected: "next run is not a reuse; it publishes a new pair" },
  { id: "D50", rule: "translate", input: "constructed: the translation drops one item's placeholder", expected: "that item Not translated (English kept); no placeholder text in zh-Hant" },
  { id: "D37", rule: "highlights", input: "constructed: one highlight cites a thread that no kept sentence cites", expected: "that highlight dropped; the other 2 shown" },
  { id: "D20", rule: "publication", input: "constructed: the detail map names a different release than the manifest", expected: "source-read failure; nothing written" },
  // Rows from the PR #35 verifier mutation pass.
  { id: "D22", rule: "run control", input: "constructed: DIGEST_CRON 37 1 * * * set; the publisher cron 7 * * * * fires", expected: "publisher" },
  { id: "D60", rule: "dry run", input: "constructed: two dry runs on the same UTC day", expected: "today.estimatedNeurons is the sum of both runs" },
  { id: "D60", rule: "dry run", input: "constructed: a dry run's stored lastRun", expected: "no objects stored; R2 keys unchanged" },
  { id: "D55", rule: "highlights call", input: "constructed: the highlights call fails; same release runs again", expected: "fallbacks counted; the next run is not a reuse" },
  { id: "D10", rule: "cache", input: "constructed: a classify batch fell back to rules; the next run has a working model", expected: "those threads are classified by the model, not served from cache" },
  { id: "D1", rule: "window", input: "constructed: a run on the captured release", expected: "window.start is window.end minus 7 days" },
  { id: "D1", rule: "window", input: "constructed: an entry whose newest activity is exactly the window start", expected: "its Detail is read and it is a candidate" },
  { id: "D20", rule: "publication", input: "constructed: the Feed manifest is v2", expected: "source-read failure; nothing written" },
  { id: "D11", rule: "publication", input: "constructed: the pointer's schema", expected: "osskb.digest-pointer.v1" },
  { id: "D13", rule: "model down", input: "constructed: a cold run classifies 12 batches", expected: "at most 4 classify calls in flight, and 4 reached" },
  { id: "D14", rule: "spend", input: "constructed: today's spend plus the next call's estimate equals the cap exactly", expected: "the call runs" },
  { id: "D14", rule: "spend", input: "constructed: a call that fails twice", expected: "both attempts add the pre-call estimate to today's spend (G21)" },
  { id: "D59", rule: "deferral", input: "constructed: a deferred run completes, then the publisher runs at the next alarm", expected: "the counter restarted: the alarm defers again" },
  { id: "D59", rule: "deferral", input: "constructed: 2 deferrals recorded, then POST /digest/run", expected: "counter cleared; the new alarm can defer 4 times" },
  // Slice 2b: Clef-flash classification, Workers AI through AI Gateway, and the Dev/Prod switches.
  { id: "D63", rule: "clef", input: "constructed: answer t1 security 0.7, clients 0.2, other 0.1, routine 0.1", expected: "topic security, topicConfidence 0.70, routine false (0.90)" },
  { id: "D63", rule: "clef", input: "constructed: answer t1 routine 0.6, other 0.4", expected: "routine section by placement() (routineConfidence 0.60)" },
  { id: "D63", rule: "clef", input: "constructed: answer t1 routine 0.55, other 0.45", expected: "routine true (0.55) but a card by placement(): below the 0.6 section gate" },
  { id: "D63", rule: "clef", input: "captured week, cold run with Clef", expected: "8 Clef requests; every state at most 1,800 tokens; at most 64 questions; excerpts at most 120 chars" },
  { id: "D63", rule: "clef", input: "constructed: the request body for one batch", expected: "model clef-flash; state [{ref, title, excerpt}] then the canary; one choice question per thread with 13 options (12 topics + routine) described by the profile, plus question end" },
  { id: "D63", rule: "clef", input: "constructed: a new comment on a thread whose title and root excerpt are unchanged", expected: "Clef features reused from cache; 0 Clef requests for it" },
  { id: "D67", rule: "clef", input: "constructed: answer for t2 missing, t3 probability 1.4", expected: "t2 and t3 get rules features; the rest model; batch counted as a fallback" },
  { id: "D67", rule: "clef", input: "constructed: the Clef request fails twice", expected: "1 retry; the batch gets rules features" },
  { id: "D68", rule: "errors", input: "binding throws \"AiError: 3036: daily free allocation of 10,000 neurons used\"", expected: "code 3036; limit" },
  { id: "D68", rule: "errors", input: "binding throws \"AI Gateway: 429 Too Many Requests\"", expected: "status 429; limit" },
  { id: "D68", rule: "errors", input: "binding throws \"Gateway spend limit reached\"", expected: "limit" },
  { id: "D68", rule: "errors", input: "binding throws \"AiError: 5007: internal server error\"", expected: "code 5007; retry" },
  { id: "D69", rule: "text response", input: "Workers AI returns {response: \"<think>…</think>{\\\"sentences\\\":[]}\", usage}", expected: "text {\"sentences\":[]}; usage kept" },
  { id: "D69", rule: "text response", input: "Workers AI returns {response: {sentences: []}} (JSON mode object)", expected: "text {\"sentences\":[]}" },
  { id: "D70", rule: "gateway", input: "DIGEST_MODEL workers-ai, DIGEST_GATEWAY_ID osskb-digest-dev, AI binding", expected: "every call passes {gateway: {id: osskb-digest-dev, skipCache: true}}" },
  { id: "D70", rule: "gateway", input: "AI binding without DIGEST_GATEWAY_ID (or DIGEST_MODEL unset)", expected: "no model: rules only" },
  { id: "D71", rule: "spend", input: "constructed: the 51st model request of one run", expected: "skipped; limited true" },
  { id: "D64", rule: "run control", input: "DIGEST_ENABLED unset (Prod)", expected: "POST /digest/run 403 disabled; an alarm runs nothing" },
  { id: "D66", rule: "dry run", input: "constructed: a dry run where the model reports usage and one call fails", expected: "result lists the error shape and a calibration ratio of reported to estimated input tokens" },
  // Rows added after the slice 2b mutation run.
  { id: "D63", rule: "clef", input: "constructed: answer t1 routine 0.45, other 0.55", expected: "topic other, topicConfidence 1.00, routine false (0.55)" },
  { id: "D63", rule: "clef", input: "constructed: answer t1 routine 0.5, other 0.25, security 0.25", expected: "topic other, topicConfidence 0.50, routine true (0.50)" },
  { id: "D63", rule: "clef", input: "constructed: 70 threads with one-letter titles and no excerpt", expected: "2 requests: 63 + 7 thread questions, each plus the canary" },
  // Rows from the PR #40 verifier (fail-safe truncation, cap, request body, provenance, calibration).
  { id: "D67", rule: "clef", input: "constructed: Clef reports 1,000 prompt tokens for a request the job estimated at 1,500", expected: "the whole batch is treated as unseen: rules features, counted as a fallback" },
  { id: "D67", rule: "clef", input: "constructed: a whole run where every Clef response reports 1 prompt token", expected: "every thread gets rules features; every batch counted as a fallback" },
  { id: "D67", rule: "clef", input: "constructed: Clef reports 1,400 prompt tokens for a request estimated at 1,500", expected: "model features (reported is at least 80% of the estimate)" },
  { id: "D71", rule: "spend", input: "constructed: a Clef decide with today's spend exactly at the cap", expected: "skipped; limited true; the pre-call estimate is at least 1 neuron" },
  { id: "D70", rule: "gateway", input: "constructed: a text-generation request through WorkersAiModel", expected: "body has messages, max_tokens, temperature 0" },
  { id: "D63", rule: "clef", input: "constructed: a run with the Clef decider", expected: "revisions.classifier is @cf/cloudflare/clef-flash with digest-clef@2" },
  { id: "D66", rule: "dry run", input: "constructed: the model reports twice the estimated input tokens", expected: "calibration ratio 2" },
  { id: "D66", rule: "dry run", input: "constructed: 2 text calls with usage, then 2 Clef requests of which 1 reports usage", expected: "calls 4, callsWithUsage 3, clefCalls 2, clefCallsWithUsage 1" },
  // Slice 2c (first Dev dry run, 2026-10-08).
  { id: "D72", rule: "canary", input: "constructed: Clef answers the canary word with probability 0.3", expected: "the whole batch is unseen: rules features, counted as a fallback" },
  { id: "D72", rule: "canary", input: "constructed: Clef answers the canary word with probability 0.9", expected: "model features" },
  { id: "D72", rule: "canary", input: "constructed: a whole run where every Clef response omits the canary answer", expected: "every thread gets rules features; clefCanaryMisses equals clefCalls" },
  { id: "D73", rule: "clef", input: "constructed: the Clef request criteria for the Kafka profile", expected: "every topic option's criterion is the profile description; revision digest-clef@2" },
  { id: "D74", rule: "call order", input: "captured week, cold run with Clef", expected: "classify, then proposal rows, then cards by score, then highlights, then translation" },
  { id: "D74", rule: "call order", input: "constructed: captured week with a 30-request ceiling", expected: "every proposal line, the highlights call, and translation ran; the lowest-score cards fall back; limited true; no item Not translated" },
  { id: "D74", rule: "call order", input: "constructed: a ModelCalls ceiling of 3 requests", expected: "the 4th request is skipped; limited true" },
  { id: "D74", rule: "call order", input: "constructed: captured week with a Clef cap of 3 requests", expected: "3 Clef requests; the other threads get rules features; limited true" },
  { id: "D75", rule: "bounds", input: "constructed: the max_tokens of each call kind in a cold run", expected: "card 500, proposal 160, highlights 800, translation 4000" },
  { id: "D75", rule: "bounds", input: "captured week, cold run with Clef", expected: "1 translation call for every item; its prompt ends with /no_think" },
  { id: "D78", rule: "style", input: "constructed: card sentences \"Omnia Ibrahim proposed Apache Kafka 4.4.0 RC4.\" and \"KIP-1349 moves snapshot frequency to bytes.\"", expected: "style {sentences 2, personLed 1}; summarizer prompt digest-prompts@2" },
  { id: "D79", rule: "coverage", input: "constructed: the translation batch returns non-JSON twice", expected: "en and zh-Hant coverage identical; notTranslated equals the zh-Hant items marked Not translated" },
  { id: "D79", rule: "coverage", input: "constructed: a complete en with an incomplete zh-Hant, retried", expected: "a new pair with identical coverage; the pointer names both new objects" },
  { id: "D80", rule: "rejections", input: "constructed: a proposal call returns JSON cut off mid-string", expected: "rejections.unparsable 1; that line null" },
  { id: "D80", rule: "rejections", input: "constructed: a card sentence says merged while its cited PR is open", expected: "rejections[\"status:merged\"] 1" },
] as const;
